### ISSUE TITLE
Discourage hard-to-use formats more prominently

### ISSUE THREAD

**Issue by haphut** [yhteentoimivuuspalvelut/ytp#6]
I'll open a new issue for this discussion that branched off from #4.

The definition of open data requires a ["machine-readable" and "convenient and modifiable form"](http://opendefinition.org/od/#open-format).

Even though avoindata.fi has a page which [discourages the use of Excel formats](https://www.avoindata.fi/fi/content/julkaise-aineistoja), currently 892 out of the 1625 published datasets are in XLS format.

Perhaps Excel formats should be more prominently discouraged when someone tries to upload data. Perhaps simple advice could be given on how to transform the data into CSV format. What do you think?

**Comment by Zharktas** [comment]
Most of the data is harvested from external sources, ie. from [Helsinki Region Infoshare](http://www.hri.fi/fi/) and [Paikkatietohakemisto](http://paikkatietohakemisto.fi/geonetwork/srv/fi/main.home) so giving advice to transform the data would not be seen by the publishers of data. Instead we have "dataset quality", which automatically rates each resource of dataset and discourages the use of XLS instead of CSV. Although the current implementation is quite simple, it wil improve in coming weeks.

**Comment by haphut** [comment]
Right. I did not realize that. Thanks.

**Comment by Zharktas** [comment]
Closing this since we have better dataset quality analyzer in place and we can't prevent Excels.
